# Generated by Django 5.2.12 on 2026-05-31 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dok_id", models.CharField(max_length=255, unique=True)),
                ("version_label", models.TextField(blank=True)),
                ("source_path", models.CharField(blank=True, max_length=512)),
                ("source_url", models.URLField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("in_force", models.BooleanField(db_index=True, default=True)),
                ("last_changed_at", models.DateTimeField(blank=True, null=True)),
                ("last_change_in_force", models.DateTimeField(blank=True, null=True)),
                ("last_changed_by", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Document version",
                "verbose_name_plural": "Document versions",
                "ordering": ["work", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_id", models.CharField(max_length=255, unique=True)),
                ("legacy_id", models.CharField(blank=True, max_length=64)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("law", "Law"),
                            ("forskrift", "Forskrift"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="law",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("historic", "Historic"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=512)),
                ("short_title", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=32)),
                ("applies_to", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("date_in_force", models.DateField(blank=True, null=True)),
                ("date_of_publication", models.DateTimeField(blank=True, null=True)),
                ("misc_information", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Document work",
                "verbose_name_plural": "Document works",
                "ordering": ["ref_id"],
            },
        ),
        migrations.CreateModel(
            name="LegalSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("requires_authentication", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Legal source",
                "verbose_name_plural": "Legal sources",
            },
        ),
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_id", models.CharField(max_length=255)),
                ("ref_id", models.CharField(blank=True, max_length=255)),
                ("heading", models.CharField(blank=True, max_length=512)),
                ("html", models.TextField()),
                ("text", models.TextField()),
                ("level", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="legaldb.documentsection",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="legaldb.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document section",
                "verbose_name_plural": "Document sections",
                "ordering": ["version", "order"],
                "unique_together": {("version", "section_id")},
            },
        ),
        migrations.AddField(
            model_name="documentversion",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="legaldb.documentwork",
            ),
        ),
        migrations.CreateModel(
            name="DocumentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("based_on", "Based on"),
                            ("changes", "Changes"),
                            ("repeals", "Repeals"),
                            ("related", "Related"),
                        ],
                        max_length=16,
                    ),
                ),
                ("evidence", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "from_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="legaldb.documentwork",
                    ),
                ),
                (
                    "to_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="legaldb.documentwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document relationship",
                "verbose_name_plural": "Document relationships",
            },
        ),
        migrations.CreateModel(
            name="DocumentOrganizationRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ministry", "Ministry"),
                            ("subunit", "Subunit"),
                            ("owner", "Owner"),
                            ("publisher", "Publisher"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_roles",
                        to="legaldb.documentwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document organization role",
                "verbose_name_plural": "Document organization roles",
            },
        ),
        migrations.CreateModel(
            name="LegalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="legaldb.legalarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal area",
                "verbose_name_plural": "Legal areas",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="documentwork",
            name="legal_areas",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="legaldb.legalarea"
            ),
        ),
        migrations.AddField(
            model_name="documentwork",
            name="legal_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="works",
                to="legaldb.legalsource",
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ministry", "Ministry"),
                            ("subunit", "Subunit"),
                            ("agency", "Agency"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suborganizations",
                        to="legaldb.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AddField(
            model_name="documentwork",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="works",
                through="legaldb.DocumentOrganizationRole",
                to="legaldb.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentorganizationrole",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="legaldb.organization"
            ),
        ),
        migrations.CreateModel(
            name="ChunkRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_id", models.CharField(max_length=255)),
                ("vector_store_id", models.CharField(db_index=True, max_length=64)),
                ("order", models.PositiveIntegerField()),
                ("char_start", models.PositiveIntegerField(blank=True, null=True)),
                ("char_end", models.PositiveIntegerField(blank=True, null=True)),
                ("token_count", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chunks",
                        to="legaldb.documentsection",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="legaldb.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk reference",
                "verbose_name_plural": "Chunk references",
                "ordering": ["version", "order"],
                "unique_together": {("version", "chunk_id")},
            },
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("work",),
                name="legaldb_single_current_version_per_work",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentrelationship",
            unique_together={("from_work", "to_work", "relation_type")},
        ),
        migrations.AlterUniqueTogether(
            name="organization",
            unique_together={("name", "type", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="documentorganizationrole",
            unique_together={("work", "organization", "role")},
        ),
    ]
